source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'FineChat' do
pod 'AFNetworking', '~> 3.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJRefresh'
pod 'Masonry'

pod 'MOBFoundation_IDFA'
pod 'SMSSDK'
end

